name: Commit Watch

on:
  - pull_request

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  commit_watch:
    name: Run Commit Watch
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0
        - uses: ./.github/actions/detect-node
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Run Commit Watch
          env:
            COMMIT_WATCH_OUTPUT_DIR: ${{ env.ARTIFACT_DIR }}/
            COMMITWATCH_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            CI_REPO_OWNER: ${{ github.repository_owner }}
            CI_REPO_NAME: ${{ github.event.repository.name }}
            CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
            CI_BASE_BRANCH: origin/${{ github.base_ref }}
          run: yarn dlx commit-watch
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: commit-watch-artifacts
            path: ${{ env.ARTIFACT_DIR }}
